// This file is auto-generated by @hey-api/openapi-ts

export type TaxReportBasicDto = {
  id: string;
  userId: string;
  year: number;
  status: 'draft' | 'submitted';
};

export type TaxReportsBasicCollection = {
  items: Array<TaxReportBasicDto>;
};

export type UnitDto = {
  description: string;
  amount?: number | null;
};

export type UnitCollection = {
  items: Array<UnitDto>;
};

export type CompensationDto = {
  company: string;
  compensations: UnitCollection;
};

export type CompensationCollection = {
  items: Array<CompensationDto>;
};

export type IncomesDto = {
  id: string;
  taxReportId: string;
  /**
   * Launatekjur og starfstengdar greiðslur
   */
  salaries?: UnitCollection | null;
  /**
   * Ökutækjastyrkur. Dagpeningar. Hlunnindi
   */
  benefits?: UnitCollection | null;
  /**
   * Lífeyrisgreiðslur. Greiðslur frá Tryggingastofnun. Aðrar bótagreiðslur, styrkir o.fl.
   */
  compensations?: CompensationCollection | null;
  createdOn: string;
  modifiedOn?: string | null;
};

export type RealEstateDto = {
  /**
   * Fastanúmer
   */
  number: string;
  address: string;
  /**
   * Fasteignamat
   */
  appraisal: number;
};

export type RealEstateCollection = {
  items: Array<RealEstateDto>;
};

export type VehicleDto = {
  /**
   * Númer
   */
  plateNumber: string;
  /**
   * Kaupár
   */
  yearOfPurchase: number;
  /**
   * Kaupverð
   */
  purchasePrice: number;
};

export type VehicleCollection = {
  items: Array<VehicleDto>;
};

export type AssetsDto = {
  id: string;
  taxReportId: string;
  /**
   * Innlendar fasteignir
   */
  realEstates?: RealEstateCollection | null;
  /**
   * Bifreiðir
   */
  vehicles?: VehicleCollection | null;
  createdOn: string;
  modifiedOn?: string | null;
};

export type RealEstateChargesDto = {
  /**
   * Kaupár
   */
  yearOfPurchase: number;
  /**
   * Staðsetning íbúðarhúsnæðis
   */
  destination: string;
  /**
   * Lánveitandi
   */
  lender: string;
  /**
   * Kennitala lánveitanda
   */
  lenderSsn: string;
  /**
   * Lánsnúmer
   */
  loanNumber: string;
  /**
   * Lántökudagur
   */
  loanDate: string;
  /**
   * Lánstími í árum
   */
  loanTotalNumberOfYears: number;
  /**
   * Heildargreiðslur ársins
   */
  totalPaymentAmountOfYear: number;
  /**
   * Afborgun á nafnverði
   */
  totalPaymentOfNominalValue: number;
  /**
   * Vaxtagjöld
   */
  interestChargesAmount: number;
  /**
   * Eftirstöðvar skulda
   */
  remainingDebtsAmount: number;
};

export type DebtDto = {
  description: string;
  /**
   * Vaxtagjöld
   */
  interestCharges: number;
  /**
   * Eftirstöðvar skulda
   */
  remainingDebtsAmount: number;
};

export type DebtCollection = {
  items: Array<DebtDto>;
};

export type DebtsDto = {
  id: string;
  taxReportId: string;
  /**
   * Vaxtagjöld vegna íbúðarhúsnæðis til eigin nota
   */
  realEstateCharges?: RealEstateChargesDto | null;
  /**
   * Aðrar skuldir og vaxtagjöld
   */
  otherDebts?: DebtCollection | null;
  createdOn: string;
  modifiedOn?: string | null;
};

export type TaxReportDto = {
  id: string;
  userId: string;
  incomes?: IncomesDto | null;
  assets?: AssetsDto | null;
  debts?: DebtsDto | null;
  year: number;
  status: 'draft' | 'submitted';
  createdOn: string;
  modifiedOn?: string | null;
};

export type AppControllerGetDataData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/';
};

export type AppControllerGetDataResponses = {
  200: unknown;
};

export type GetTaxReportsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/tax-reports';
};

export type GetTaxReportsResponses = {
  /**
   * ok
   */
  default: TaxReportsBasicCollection;
};

export type GetTaxReportsResponse =
  GetTaxReportsResponses[keyof GetTaxReportsResponses];

export type CreateTaxReportData = {
  body: TaxReportDto;
  path?: never;
  query?: never;
  url: '/tax-reports';
};

export type CreateTaxReportResponses = {
  /**
   * ok
   */
  200: TaxReportDto;
};

export type CreateTaxReportResponse =
  CreateTaxReportResponses[keyof CreateTaxReportResponses];

export type UpdateTaxReportData = {
  body: TaxReportDto;
  path?: never;
  query?: never;
  url: '/tax-reports';
};

export type UpdateTaxReportResponses = {
  /**
   * ok
   */
  200: TaxReportDto;
};

export type UpdateTaxReportResponse =
  UpdateTaxReportResponses[keyof UpdateTaxReportResponses];

export type DeleteTaxReportData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/tax-reports/{id}';
};

export type DeleteTaxReportResponses = {
  /**
   * ok
   */
  204: void;
};

export type DeleteTaxReportResponse =
  DeleteTaxReportResponses[keyof DeleteTaxReportResponses];

export type ViewTaxReportData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/tax-reports/{id}';
};

export type ViewTaxReportResponses = {
  /**
   * ok
   */
  200: TaxReportDto;
};

export type ViewTaxReportResponse =
  ViewTaxReportResponses[keyof ViewTaxReportResponses];

export type ClientOptions = {
  baseUrl: string;
};
